name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Lint & Typecheck
        run: |
          pip install flake8 mypy
          flake8 app/
          mypy app/
      - name: Unit tests
        run: |
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

  docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/mlops-pipeline:${{ github.sha }} .
      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/mlops-pipeline:${{ github.sha }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: kubernetes/deployment.yaml,kubernetes/service.yaml
          images: |
            ${{ secrets.DOCKER_REGISTRY }}/mlops-pipeline:${{ github.sha }}
